[pytest]
addopts =
    --alluredir=allure-results
    --clean-alluredir
    -v
testpaths = tests
markers =
    registration: Registration tests
    search: Search with price filter tests
    cart: Cart tests
