from http import HTTPStatus


HTTP_BAD_REQUEST = HTTPStatus.BAD_REQUEST
HTTP_CREATED = HTTPStatus.CREATED
HTTP_FORBIDDEN = HTTPStatus.FORBIDDEN
HTTP_FOUND = HTTPStatus.FOUND
HTTP_INTERNAL_SERVER_ERROR = HTTPStatus.INTERNAL_SERVER_ERROR
HTTP_NO_CONTENT = HTTPStatus.NO_CONTENT
HTTP_NOT_FOUND = HTTPStatus.NOT_FOUND
HTTP_OK = HTTPStatus.OK
