"""Data fixtures — factory-backed test inputs, API cart helper."""
from dataclasses import asdict
from typing import NamedTuple

import pytest

from utils.api_client import create_cart
from utils.data_loader import get_config
from utils.factories import (
    CartScenario,
    LoginCredentials,
    RegistrationData,
    SearchData,
    make_cart_scenario,
    make_invalid_credentials,
    make_registration,
    make_search,
)


class ApiCart(NamedTuple):
    """Named result of the api_cart fixture — supports both attribute and positional access."""
    ocsessid: str
    products: list
    max_total: float
    max_price: float


@pytest.fixture
def registration_data() -> dict:
    """Unique registration fields per test, generated by Faker."""
    return asdict(make_registration())


@pytest.fixture
def dynamic_registration() -> RegistrationData:
    """Typed RegistrationData for tests that prefer the dataclass API."""
    return make_registration()


@pytest.fixture
def search_data() -> SearchData:
    """SearchData driven by config values, with Faker-backed fallbacks."""
    cfg = get_config()
    return make_search(
        query=cfg.get("test_search_query", "MacBook"),
        max_price=cfg.get("test_max_price", 700.0),
        limit=cfg.get("test_search_limit", 5),
    )


@pytest.fixture
def cart_scenario() -> CartScenario:
    """CartScenario wired for a MacBook search with a realistic price cap."""
    return make_cart_scenario()


@pytest.fixture
def invalid_credentials() -> LoginCredentials:
    """Random credentials guaranteed not to match any real account."""
    return make_invalid_credentials()


@pytest.fixture
def api_cart(app_url: str, cart_scenario: CartScenario) -> ApiCart:
    """Populate a cart via the OpenCart REST API (no browser).

    Returns an ApiCart named tuple; callers can use attribute access
    (``api_cart.ocsessid``) or positional unpacking for backward compatibility.

    Each call gets its own OCSESSID so parallel workers never share
    server-side cart state.  Inject the cookie into the Playwright context
    before navigating::

        context.add_cookies([{"name": "OCSESSID", "value": api_cart.ocsessid, "url": app_url}])
    """
    ocsessid, products = create_cart(
        base_url=app_url,
        query=cart_scenario.query,
        max_price=cart_scenario.max_price,
        limit=cart_scenario.limit,
    )
    return ApiCart(
        ocsessid=ocsessid,
        products=products,
        max_total=cart_scenario.max_total,
        max_price=cart_scenario.max_price,
    )
